CREATE TABLE IF NOT EXISTS Genre (
	Genre_ID SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT null
);

CREATE TABLE IF NOT EXISTS Singers (
	Singer_ID SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS List_genres (
	ID SERIAL PRIMARY KEY,
	Genre_ID INTEGER NOT NULL REFERENCES Genre(Genre_ID),
	Singer_ID INTEGER NOT NULL REFERENCES Singers(Singer_ID)
);

CREATE TABLE IF NOT EXISTS Albums (
	Album_ID SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	Release_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS List_albums (
	ID SERIAL PRIMARY KEY,
	Singer_ID INTEGER NOT NULL REFERENCES Singers(Singer_ID),
	Album_ID INTEGER NOT NULL REFERENCES Albums(Album_ID)
);

CREATE TABLE IF NOT EXISTS Tracks (
	Track_ID SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	Album_ID INTEGER NOT NULL REFERENCES Albums(Album_ID),
	Duration NUMERIC	
);

CREATE TABLE IF NOT EXISTS Collection (
	Collection_id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL,
	Release_date DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Collection_tracks (
	ID SERIAL PRIMARY KEY,
	Track_ID INTEGER NOT NULL REFERENCES Tracks(Track_ID),
	Collection_id INTEGER NOT NULL REFERENCES Collection(Collection_id)
);
